Update firewall.rst
NethServer/docs pull request #543
Opened 2020-11-18 07:48 UTC by cotosso

better explanation of ALG

2020-11-18 11:09 UTC, filippocarletti approved these changes

2020-11-18 11:24 UTC, gsanchietti requested changes

2020-11-18 11:24 UTC, gsanchietti commented on administrator-manual/en/firewall.rst
> +Application-level gateway is a security component that augments a firewall or NAT employed in a computer network.
Use the same form found inside the title:
```suggestion
Application level gateway is a security component that augments a firewall or NAT employed in a computer network.
```

2020-11-18 11:24 UTC, gsanchietti commented on administrator-manual/en/firewall.rst
> +ALG inspect and rewrite specific network packets and automatically opens required ports.
```suggestion
ALG inspects and rewrites specific network packets and automatically opens required ports.
```

2020-11-18 11:24 UTC, gsanchietti commented on administrator-manual/en/firewall.rst
> +Since some PBXs may not work properly in the presence of ALG on SIP and H.323 protocols, if you're experiencing audio and call problems with your PBX or VoIP client try to disable SIP-ALG and H.323-A
> in the presence 

It's not a common Ensligh form, please rephrase it.

2020-11-18 11:24 UTC, gsanchietti commented on administrator-manual/en/firewall.rst
> +ALG is enabled by default on NethSecurity, it supports many application protocols (like FTP, SIP and so on), allowing them to operate through NAT.
Do not use the product name, but use the `product` macro.

2020-11-19 13:22 UTC, gsanchietti commented
There are still required changes, please request the review again when done.

2020-11-19 13:38 UTC, gsanchietti approved these changes

2020-11-19 13:39 UTC, merged